/*global $*/
$("document").ready(function(){
    
    var musicGenre = "metal";
    
    
    //This function return a random option iside the music genre.
    function randomOption(data){
        var genreOptions = data[musicGenre];
        var len = Object.keys(genreOptions).length;
        var randomNum = Math.floor(Math.random() * len);
        var randomKey = Object.keys(genreOptions)[randomNum];
        
        return randomKey;
    }
    
    
    // Using the option generated by previuos function, get the random names
    function randomName(data){
        var option = randomOption(data);
        var obj = data[musicGenre][option];
        
         console.log(option);
        
        if(option === "optionA" || option === "optionB") {
            var random1st = Math.floor(Math.random() * obj.firstWord.length);
            var random2nd = Math.floor(Math.random() * obj.secondWord.length);
            console.log(obj.firstWord[random1st] + " " + obj.secondWord[random2nd]);
        } else if( option === "optionD") {
            var randomD= Math.floor(Math.random() * obj.length);
            console.log(obj[randomD]);
        }
    }
    
    $.getJSON("js/options.json", randomName);
  
    
})


  