/*global $*/
$("document").ready(function(){
    
    var musicGenre ;
    
    
    //This function return a random option iside the music genre.
    function randomOption(data){
        var genreOptions = data[musicGenre];
        var randomNum = Math.ceil(Math.random() * 100);
        var index;
        
        // % chances on every option
        if(randomNum < 3) {
           index = 0;
        } else if (randomNum < 98){
           index = 1;
        } else {
           index = 2;
        }
        
        var randomKey = Object.keys(genreOptions)[index];
        
        return randomKey;
    }
    
    
    // Using the option generated by previuos function, get the random names
    function randomName(data){
        var option = randomOption(data);
        var obj = data[musicGenre][option];
    
        if(option === "optionA" || option === "optionB") {
            var random1st = Math.floor(Math.random() * obj.firstWord.length);
            var random2nd = Math.floor(Math.random() * obj.secondWord.length);
            $("#band-name").html(obj.firstWord[random1st] + " " + obj.secondWord[random2nd]);
            console.log(obj.firstWord[random1st] + " " + obj.secondWord[random2nd]);
        } else if( option === "optionC") {
            var randomC= Math.floor(Math.random() * obj.length);
            $("#band-name").html(obj[randomC]);
            console.log(obj[randomC]);
        }
    }
    
   function getName(){
       $.getJSON("js/options.json", randomName); 
   }
      
      
      function chooseMetal(){
          musicGenre = "metal";
          getName();
      }
      
      function chooseStoner(){
          musicGenre = "stoner";
          getName();
      }
      
      
      
      $("#metal").on("click", chooseMetal);
      $("#stoner").on("click", chooseStoner);
      $("#random").on("click", getName);
      
      
      
})


  